name: text_search
description: Simple in-memory fuzzy text searching library.
version: 0.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  edit_distance: ^0.5.0-nullsafety.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic:
  test:
