name: text_search
description: Simple in-memory fuzzy text searching library.
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  edit_distance: ^0.5.0-nullsafety.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.1
