name: text_search
description: Simple in-memory fuzzy text searching library.
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  edit_distance:
  tuple:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  ff_protos:
    path: ../ff_protos